on: [workflow_dispatch]

jobs:
  build-doc-job:
    runs-on: ubuntu-latest
    name: A job to transform markdown into docx
    steps:
      - name: checkout step
        uses: actions/checkout@v4
      - name: build doc
        id: pandoc
        uses: ZhongYic00/pandoc-customized-action@v1
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: workspace_artifacts
          path: ${{ github.workspace }}/docs/reports/gen/
